default_language_version:
  python: python3.14
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.29
    hooks:
      - id: uv-sync
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff-check
      - id: ruff-format
